name: urbandog
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: xikwy8-zawvat-tImpyc
      MYSQL_DATABASE: wp_ud_db
      MYSQL_USER: wp_ud_user
      MYSQL_PASSWORD: 8Lm@P$4zQxN!9kTrW2v
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_ud_user
      WORDPRESS_DB_PASSWORD: 8Lm@P$4zQxN!9kTrW2v
      WORDPRESS_DB_NAME: wp_ud_db
      WORDPRESS_DEBUG: "true"
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        @ini_set( 'display_errors', 0 );
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wp_ud_user
      PMA_PASSWORD: 8Lm@P$4zQxN!9kTrW2v

volumes:
  db_data:
  wordpress_data: